rm -rf BAM/
rm -rf benchmark/
rm -rf BWA/
rm -rf fastp*
rm -rf FeatureCounts/
rm -rf finalReport*
rm -rf QC/
rm -rf SAM/
rm -rf FASTQ/CONCATENATED/
rm -rf FASTQ/TRIMMED/
rm -rf logs/
rm -rf QUANTIFICATION/
rm -rf RSEM/
rm -rf Stringtie/
rm -rf .snakemake/
rm -rf _STARtmp/