project-folder: "/scratch/project_2002561/MastitisChallenge/RNASeq-Analysis"                   
pipeline-folder: "/scratch/project_2002561/pipeline"
pipeline-config: "Snakebite-RNAseq_config.yaml"
server-config: "Snakebite-RNAseq_server-config.yaml"
rawdata-folder: "FASTQ/RAW"
samplesheet-file: "samplesheet.tsv"
sampleinfo-file: ""
genome: "Reference/Bos_taurus.ARS-UCD1.2.dna.toplevel.fa"      
annot:  "Reference/Bos_taurus.ARS-UCD1.2.100.gtf"
local-scratch: $LOCAL_SCRATCH
tmp-folder: "tmp"
contamination-folder: "Reference/Contamination"
contamination-refs: ["GCF_000005845.2_ASM584v2_genomic.fna", "GCF_000013425.1_ASM1342v1_genomic.fna", "SILVA_138.1_LSURef_tax_silva.fasta"]

params:
  fastp:
    trim_front1: 12
    trim_tail1: 0
    trim_front2: 0
    trim_tail2: 0
  rsem:
    paired: "--paired-end"                                                      # For SE reads, set here ""
  star:
    genomeSAindexNbases: 14
    overhang: 74
    limitGenomeGenerateRAM: 300647710720
    sparseD: 1                  # For large genomes, set this value higher
    genomeChrBinNbits: 18       # Reduce this for larger genomes
    mode: ""                    # Set this to "meta" for metatranscriptome studies, to run STAR without annotation
  stringtie:
    tpm: 2
  featurecounts:
    attributetype: "gene_id"    # Option for RNA-seq: "gene_id", for metagenomics: "ID" (If output of Snakebite-Metagenomics is used as input files)
    featuretype: "exon"         # Options are "exon", "transcript" and "gene". For Metagenomics "CDS"

